### ISSUE TITLE
Be sensitive to token in tests

### ISSUE THREAD

**Issue by ManuelBahr** [blue-yonder/azure-cost-mon#2]
Currently, the test_token test runs through but actually should fail. The test obviously is not sensitive to the token setting. In practice it works, but the test should represent that behaviour.

**Comment by MathMagique** [comment]
This is the test in question: https://github.com/blue-yonder/azure-cost-mon/blob/master/tests/test_app.py#L32

**Comment by ManuelBahr** [comment]
This should be the trick to check for the header https://github.com/getsentry/responses#request-callback
